Algoritmo "TABUADA USANDO ENQUANTO"

Var
   // Seção de Declarações das variáveis

   cont, num: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   Escreval("Digite um número")
   leia (num)
   cont <- 1
   
   enquanto (cont <= 10)faca
  // para i de 1 ate 10 faca
      escreval (num," X ",cont," = ", num*cont)
      cont<- cont + 1
      fimenquanto
   //fimpara

Fimalgoritmo