Algoritmo "Aula 6_7 - EXERCICIO 3"

Var
   // Seção de Declarações das variáveis
   cont,num: inteiro
   resposta: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   cont <- 10
   repita
   timer 1000
      Escreval ("CONTAGEM REGRESSIVA ")
      Escreval (cont)
      Cont <- cont - 1
   ate (cont = 0)
   Escreval ("SEU TEMPO ACABOU!")


Fimalgoritmo