Algoritmo "Exercio 14"

Var
// Seção de Declarações das variáveis 

A,B: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Infome 2 número interos e veja se o primeiro é maior que o segundo")
 leia(a,b)
  escreval ("a = ", a, " b = " , b)

  se(a>b)entao
  escreval ("A é maior que B")
  senão
  escreval ("B é maior que A")
  fimse


Fimalgoritmo