Algoritmo "Exercio 18"

Var
// Seção de Declarações das variáveis 

A: inteiro
B: inteiro
C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


 escreval ("Infome 3 números(A,B e C) inteiros e veja se a soma A+B é igual a C. ")
 leia(A,B,C)
  escreval ("A=", a , "  B= " , b , "  C= ", C)

  se(A+B=C)entao
  escreval ("Verdadeiro, a soma de A+B é igual a C")
  senão
  escreval ("Falso, a soma A+B não é igual a C")
  fimse


Fimalgoritmo