Algoritmo "Exercio 15"

Var
// Seção de Declarações das variáveis 

A: inteiro
B: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 



 escreval ("Infome um número interos e verifique se são diferentes")
 leia(a,b)
  escreval ("A=", a , " B= " , b)

  se(a<>b)entao
  escreval ("Verdadeiro, A é diferante a B")
  senão
  escreval ("Falso, A não é diferente a B")
  fimse


Fimalgoritmo