Algoritmo "Exercio 15"

Var
// Seção de Declarações das variáveis 

A: inteiro
B: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
B := 10


 escreval ("Infome um número intero e verifique se é igual a 10")
 leia(a)
  escreval ("A=", a , " B= " , b)

  se(a=b)entao
  escreval ("Verdadeiro, A é igual a B")
  senão
  escreval ("Falso, A não é  igual a B")
  fimse


Fimalgoritmo