Algoritmo "Exercio 17"

Var
// Seção de Declarações das variáveis 

A: real
B: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 B := 5


 escreval ("Infome um número real(com virgula) e veja se ele é menor ou igual a 5")
 leia(A)
  escreval ("A=", a , " B= " , b)

  se(A<=B)entao
  escreval ("Verdadeiro, A é menor ou igual a B")
  senão
  escreval ("Falso, A não é maior a B")
  fimse


Fimalgoritmo