Algoritmo "Exercício 21"

Var
// Seção de Declarações das variáveis 

A: inteiro
B: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Informe 2 números inteiros para verificar se pelo menos 1 é negativo")
leia (A,B)
escreval ("A=", a, " B=" , B)

 se (A > 0) ou (B > 0) entao
    escreval("VERDADEIRO")
   senao
      escreval("FALSO")
   fimse

Fimalgoritmo