Algoritmo "Exercio 19"

Var
// Seção de Declarações das variáveis 

A: inteiro
B: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


 escreval ("Infome 2 números interos(A e B).Vamos ver se A é maior que o dobro de B.) . ")
 leia(A,B)
  escreval ("A=", a , "  B= " , b)

  se(A>(2*B))entao
  escreval ("Verdadeiro, A é maior que o dobro de B")
  senão
  escreval ("Falso,A é menor que o dobro de B")
  fimse


Fimalgoritmo