Algoritmo "AULA 9 (VETOR) - EXEMPLO LER E MOSTRAR"

Var
// Seção de Declarações das variáveis 

i: inteiro
v: vetor [0..4] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para i de 0  ate 4 faca
   Escreva ("Digite v[",i,"]:")
   Leia(v[i])
   fimpara
   
   
   Escreval("")
   Escreval("Conteúdo do vetor: ")
   para i de 0 ate 4 faca
   Escreval ("v[",i,"] = ",v[i])
   fimpara


Fimalgoritmo