package javacrudapp;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author TI
 */
public class CrudAppFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrudAppFrame.class.getName());

    /**
     * Creates new form CrudAppFrame
     */
    private int IdUsuarioSelecionado = -1;

    public CrudAppFrame() {

        initComponents();

        try {
            loadUserData();
        } catch (SQLException ex) {
            System.getLogger(CrudAppFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
                    
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        SobrenomeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        CidadeTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        AtualizarButton = new javax.swing.JButton();
        DeletarButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Usuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 200));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRUD COM INTERFACE GRÁFICA");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome: ");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sobrenome:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cidade:");

        nomeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        SobrenomeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CidadeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AddButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AddButton.setText("Adicionar");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        AtualizarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarButtonActionPerformed(evt);
            }
        });

        DeletarButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DeletarButton.setText("Deletar");
        DeletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1074, 1074, 1074)
                        .addComponent(jLabel5)
                        .addGap(59, 59, 59)
                        .addComponent(CidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(AddButton)
                        .addGap(330, 330, 330)
                        .addComponent(AtualizarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeletarButton)
                        .addGap(288, 288, 288))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(SobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(211, 211, 211))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(SobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeletarButton)
                    .addComponent(AtualizarButton)
                    .addComponent(AddButton))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Tabela_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sobrenome", "Email", "Cidade"
            }
        ));
        Tabela_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_UsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Usuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1750, 1750, 1750)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1908, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String addNome = nomeTextField.getText();
        String addSobrenome = SobrenomeTextField.getText();
        String addEmail = emailTextField.getText();
        String addCidade = CidadeTextField.getText();

        if (addNome.isEmpty() || addSobrenome.isEmpty() || addEmail.isEmpty() || addCidade.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos", "ERRO", JOptionPane.ERROR_MESSAGE);

        } else {
            Usuario novoUsuario = new Usuario(0, addNome, addSobrenome, addEmail, addCidade);
            UsuarioDAO userDao;

            try {
                userDao = new UsuarioDAO();
                int res = userDao.InserirUsuario(novoUsuario);
                if (res == 1) {
                    JOptionPane.showMessageDialog(this, "Usuario criado com sucesso", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                    this.clearForm();
                    loadUserData();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o usuario", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o usuario", "ERRO", JOptionPane.ERROR_MESSAGE);
            }

        }


    }//GEN-LAST:event_AddButtonActionPerformed

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed

        String addNome = nomeTextField.getText();
        String addSobrenome = SobrenomeTextField.getText();
        String addEmail = emailTextField.getText();
        String addCidade = CidadeTextField.getText();

        if (addNome.isEmpty() || addSobrenome.isEmpty() || addEmail.isEmpty() || addCidade.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos", "ERRO", JOptionPane.ERROR_MESSAGE);

        } else {
            if (IdUsuarioSelecionado != -1) {
                Usuario AtualizarUsuario = new Usuario(IdUsuarioSelecionado, addNome, addSobrenome, addEmail, addCidade);
                UsuarioDAO usuarioDao;
                try {
                    usuarioDao = new UsuarioDAO();
                    int res = usuarioDao.updateUsuario(AtualizarUsuario);
                    if (res == 1) {
                        JOptionPane.showMessageDialog(this, "Usuario atualizado com sucesso", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                        this.clearForm();
                        loadUserData();
                        IdUsuarioSelecionado = 1;
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void DeletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarButtonActionPerformed
        if (IdUsuarioSelecionado != -1) {
            int confirmacao = JOptionPane.showConfirmDialog(this, "Você tem certeza que quer deletar o usuario selecionado?", "Confirme a ação.", JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_NO_OPTION) {
                UsuarioDAO usuarioDao;
                try {
                    usuarioDao = new UsuarioDAO();
                    usuarioDao.deleteUsuario(IdUsuarioSelecionado);
                    JOptionPane.showMessageDialog(this, "Usuário deletado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    this.clearForm();
                    loadUserData();
                    IdUsuarioSelecionado = -1;
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao deletar", "ERRO", JOptionPane.ERROR_MESSAGE);
                }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeletarButtonActionPerformed

    private void Tabela_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_UsuariosMouseClicked
        int linhaSelecionada = Tabela_Usuarios.getSelectedRow();
        if (linhaSelecionada != -1) {
            IdUsuarioSelecionado = Integer.parseInt(Tabela_Usuarios.getValueAt(linhaSelecionada, 0).toString());
            nomeTextField.setText(Tabela_Usuarios.getValueAt(linhaSelecionada, 1).toString());
            SobrenomeTextField.setText(Tabela_Usuarios.getValueAt(linhaSelecionada, 2).toString());
            emailTextField.setText(Tabela_Usuarios.getValueAt(linhaSelecionada, 3).toString());
            CidadeTextField.setText(Tabela_Usuarios.getValueAt(linhaSelecionada, 4).toString());
        }


    }//GEN-LAST:event_Tabela_UsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrudAppFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JTextField CidadeTextField;
    private javax.swing.JButton DeletarButton;
    private javax.swing.JTextField SobrenomeTextField;
    private javax.swing.JTable Tabela_Usuarios;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTextField;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        nomeTextField.setText("");
        SobrenomeTextField.setText("");
        emailTextField.setText("");
        CidadeTextField.setText("");

    }

    private void loadUserData() throws SQLException {
        UsuarioDAO userDao = new UsuarioDAO();
        List<Usuario> usuarios = userDao.getUsuarios();
        String[][] data = new String[usuarios.size()][5];

        for (int i = 0; i < usuarios.size(); i++) {
            data[i][0] = String.valueOf(usuarios.get(i).getId());
            data[i][1] = usuarios.get(i).getNome();
            data[i][2] = usuarios.get(i).getSobrenome();
            data[i][3] = usuarios.get(i).getEmail();
            data[i][4] = usuarios.get(i).getCidade();
        }

        String[] nomeColuna = {"Id", "Nome", "Sobrenome", "Email", "Cidade"};
        Tabela_Usuarios.setModel(new javax.swing.table.DefaultTableModel(data, nomeColuna));

    }

}
